info:
  app:
    name: Unit Test

configuration:  
  projectName: unit-test
    
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/unittest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    instance_id: ${random.value}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-request-size: 15MB

